name: CI / CD for Angular
on:
  push:
    branches: [ "develop" ]

jobs:
  build-dev-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: npm install

      - name: Tests
        run: npm run ci:test

      - name: Build
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-avz -e"
            SOURCE: "dist/fe-ink"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: "/dist/fe-ink"

